name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v7

      - name: Initialize Node Runtime
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Extract Modules & Build Target
        run: |
          npm ci
          npm run build

      - name: Stage Deployment Platform
        uses: actions/configure-pages@v6

      - name: Transport Static Target Bundles
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'dist'

      - name: Execute Live Edge Deployment
        id: deployment
        uses: actions/deploy-pages@v5
